server:
  port: 9009

spring:
  datasource:
    driver-class-name: 'org.postgresql.Driver'
    password: 'postgres'
    url: 'jdbc:postgresql://localhost:5432/postgres'
    username: 'postgres'

  liquibase:
    change-log: "classpath:db/db.changelog-main.yaml"
    user: 'postgres'
    password: 'postgres'
    enabled: true

  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: TRACE
    org.springframework.security.oauth2: TRACE



